### ISSUE TITLE
Handling of requests containing test codes

### ISSUE THREAD

**Issue by SebastianRehfeldt** [gtuk/diga-api-service#1]
Sending test codes using this service makes sense to me to try out the different api endpoints and also to test integrations of this service. However, in production setups it might be better to disallow sending requests with test codes. Potential solutions:
- have a setting which disables sending requests for test codes
- returning `is_test_code` in the api responses so it can be handled at caller side.

**Comment by gtuk** [comment]
Really good point. I already had on my internal roadmap. I will most likely go with a setting that is configurable through the env variables to disable test codes

**Comment by gtuk** [comment]
#3

**Comment by gtuk** [comment]
DISABLE_TESTCODES env variable can be set now. Default value is true
