### ISSUE TITLE
Include diga error code for code validation requests in response

### ISSUE THREAD

**Issue by bokchan** [gtuk/diga-api-service#10]
If a code validation request fails the service returns a generic response with http status 400, e.g.: 

```json
{
    "timestamp": "2021-08-11T14:39:16.682+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/validate/AAAAAAAAAAAAAAAA"
}
```

In the case where the request to `diga-api-client` succeeds but [response.isHasError() == true](https://github.com/gtuk/diga-api-service/blob/main/src/main/kotlin/dev/gtuk/diga/DigaService.kt#L86) it would be helpful if the original errors from the `DigaCodeValidationResponse` could be included in the response from the `diga-api-service` as well. 

- It will allow the client/us to determine which error message to show to the user  
- Being able to store the response with the original diga error code directly in our db backend makes it easier to integrate it with our internal monitoring systems.

Using the numeric error codes seems more consistent as they are language independent and also found in official DiGA documentation. 

A possible response format could be: 

```json
{
    "timestamp": "2021-08-11T14:39:16.682+00:00",
    "status": 400,
    "error": "Bad Request",
    "digaErrorCode": 102, 
    "digaErrorText": "Freischaltcode / Rezeptcode nicht gefunden: AAAA AAAA AAAA AAAA",  // optional
    "path": "/validate/AAAAAAAAAAAAAAAA"
}
```

One complication is that `AbstractDigaApiResponse` defines `errors` as a List so it might be that the response format should reflect this. 

```json
{
  "timestamp":"2021-08-11T14:39:16.682+00:00",
  "status":400,
  "error":"Bad Request",
  "digaErrors":[
    {
      "errorCode":102,
      "errorText":"Freischaltcode / Rezeptcode nicht gefunden: AAAA AAAA AAAA AAAA" // optional
    }
  ],
  "path":"/validate/AAAAAAAAAAAAAAAA"
}
```

**Comment by gtuk** [comment]
Sorry for the late reply. That's a pretty good point. I will include it these information in an additional field/list errorDetails.
I am quite busy right now with other things so it will take probably around a week

**Comment by bokchan** [comment]
Hi @gtuk . That sounds great.

**Comment by gtuk** [comment]
@bokchan i actually looked now at this feature and realized i already exposed a message property. The response is currently looks like this:
```
{
    "timestamp": "2021-08-21T18:34:08.465+00:00",
    "status": 400,
    "error": "Bad Request",
    "message": "DigaCodeValidationResponseError(errorCode=REQUEST_OR_DATA_INVALID, errorText=Anfrage oder Datei ungültig)",
    "path": "/validate/77AAAAAAAAAAAGIS"
}
```

The problem was that the property message was omitted when running the API in production.
I just pushed a new release which exposed this field also in the production env. 
I hope this already helps, but i will still look a bit more into this feature in order to improve the error logging

**Comment by bokchan** [comment]
HI @gtuk . That's great. Having the diga error code and text wrapped in the `message` field is absolutely fine. 
Happy it didn't require any changes apart from a release  :)

**Comment by gtuk** [comment]
Ok perfect. If this is already enough for now i will close this issue. In case there are some more information needed in the future feel free to open a new request
