### ISSUE TITLE
Using the service for two DiGAs

### ISSUE THREAD

**Issue by kennyx46** [gtuk/diga-api-service#19]
Hi! 
First of all thanks for this project, it helped us a lot.

We would like to use the service to validate the codes for two DiGAs in the future. As far as I see this might not be possible with the current implementation. I see two possible ways at this point:
1. Run a separate instance of this service with a different configuration.
2. Add two additional endpoints (e.g. `validate_diga2` and `bill_diga2`) for the second DiGA and implement some way to switch between the configurations.

Am I going in the right direction or am I missing something?
Thanks!

**Comment by fongie** [comment]
I think youre going in the right direction :) at least the https://github.com/alex-therapeutics/diga-api-client does not support any kind of switching right now

**Comment by kennyx46** [comment]
Ok, thanks a lot for the quick answer.
