### ISSUE TITLE
Extend code validation response with the xml file from diga api response

### ISSUE THREAD

**Issue by SebastianRehfeldt** [gtuk/diga-api-service#5]
We have noticed in section `4.4 - Protokollierung` [here](https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/digitale_gesundheitsanwendungen/technische_anlagen_aktuell_7/DiGA_Anlage_1_Technische_Anlage_zur_RL_V1.1_20210225.pdf) that it is required to log the interactions with the DiGA api. 

```
Die Protokollierung muss die folgenden Mindestinhalte umfassen:
- Eindeutige Bezeichnung der Kommunikationspartner (Institutionskennzeichen)
- Zeitstempel im Format „yyyy-MM-dd HH:mm:ss“, basierend auf deutscher Zeit
- Prozesskennzeichen (Prüfung Freischaltcode / Rezeptcode / Abrechnung)
- Freischaltcode / Rezeptcode
- Verarbeitungskennzeichen (fehlerfrei/fehlerhaft)
```

Translated fields:
```
- ik numbers
- timestamp in German timezone
- value for `verfahren`
- prescription code
- flag if valid or not
```

In the current json response of this service we only get parts of this data. Also it might be a good idea to store the response xml (on caller-side) after making the validation request. Therefore, it would be great if this service could return the xml file in addition to the existing response format. In its' simplest form the xml could just be returned as text string.

**Current Response**
```json
{
    "code": "77AAAAAAAAAAAAAX",
    "digavId": "00451000",
    "dayOfServiceProvision": "2021-06-02"
}
```

**Proposed Change**
```json
{
    "code": "77AAAAAAAAAAAAAX",
    "digavId": "00451000",
    "dayOfServiceProvision": "2021-06-02",
    "xmlResponse": "<?xml version="1.0" ...>..."
}
```

All the required data for logging can be extracted from the `xml_response` on the caller-side. Additionally, it could make sense to return a boolean field `isTestCode` which denotes if the code was a test code or not.

What do you think @gtuk ?

**Comment by gtuk** [comment]
Hi, I'm not sure if returning the raw xml response would give you enough infos. Here is an example response:

```
<Pruefung_Freischaltcode
        xmlns="http://www.gkv-datenaustausch.de/XML-Schema/EDFC0_Pruefung/2.0.0" nachrichtentyp="ANT"
        verfahrenskennung="TDFC0" absender="123456789" empfaenger="102114819" version="002.000.000"
        gueltigab="2020-07-01">
    <Antwort>
        <IK_DiGA_Hersteller>123456789</IK_DiGA_Hersteller>
        <IK_Krankenkasse>102114819</IK_Krankenkasse>
        <DiGAVEID>00329000</DiGAVEID>
        <Freischaltcode>77AAAAAAAAAAAAAX</Freischaltcode>
        <Tag_der_Leistungserbringung>2021-05-19</Tag_der_Leistungserbringung>
    </Antwort>
</Pruefung_Freischaltcode>
```
The date for example wouldn't be in the expected format "yyyy-MM-dd HH:mm:ss" and also some other infos couldn't be easily extracted from the raw response.
As far as I understood the document it is more about request/response logging on the diga manufactors side (e.g auditing)

Nevertheless i think it's good to be transparent to the underlying diga-api-client and expose the fields that the client is giving us.

**Comment by gtuk** [comment]
@SebastianRehfeldt could you check here if this would be sufficient for you #6

**Comment by SebastianRehfeldt** [comment]
Hey @gtuk thanks for having a look so fast! :)

> As far as I understood the document it is more about request/response logging on the diga manufactors side (e.g auditing)

Yes, this is also what I understood. From our backend we can make a code validation request to the diga-api-service but need to do the request/response logging in our backend. But without the xml file we wouldn't have all the required data for this.

>  I'm not sure if returning the raw xml response would give you enough infos

I think it should be alright. At least it provides the data which we otherwise wouldn't have access to in our Backend. Trying to go through the initial list:

- **ik numbers:** can be extracted from the xml
- **timestamp:** can be created easily on caller side according to DiGA specification
- **verfahren:** can be extracted from xml
- **prescription code:** in json response already
- **flag if valid or not**: can be set depending on response status code

> some other infos couldn't be easily extracted from the raw response.

Yes, it will require parsing of the response on the caller-side as well. Ideally, the diga-api-service could return the fields in json. However, for auditing and debugging purposes it might still be a good idea to have access to the raw DiGA response.

Btw. as I still have not all prerequisites to test out this service myself, how does the error responses look like? There it would also be great to expose the raw xml response from DiGA api.

**Comment by gtuk** [comment]
Currently the diga-api-client is handling catching invalid validation codes already and throws a DigaCodeValidationException. The response from this is service is then:
```
{
    "timestamp": "2021-06-11T08:21:34.924+00:00",
    "status": 400,
    "error": "Bad Request",
    "message": "DigaCodeValidationResponseError(errorCode=CODE_CANCELLED, errorText=Freischaltcode storniert)",
    "path": "/validate/77AAAAAAAAAAADFF"
}
```

**Comment by gtuk** [comment]
#6 merged

**Comment by SebastianRehfeldt** [comment]
Cool, thanks for adding the example response 👍
